// GENERATED by scripts/gen-media-meta.mjs — do not edit by hand.
// Probed from public/media/*_full.{mp4,jpg}, the rendition the page displays.
// Regenerate with: npm run gen:media-meta

export type MediaMeta = { width: number; height: number; durationSec: number }

export const MEDIA_META: Record<string, MediaMeta> = {
  file10: { width: 540, height: 720, durationSec: 5.03 },
  file11: { width: 1280, height: 720, durationSec: 9.97 },
  file12: { width: 1280, height: 720, durationSec: 12 },
  scary_monsters_remake: { width: 1080, height: 1440, durationSec: 0 },
}

/** The 240p encode's box. Only its aspect ratio matters, and only as a guard. */
export const THUMB_META: Record<string, { width: number; height: number }> = {
  file10: { width: 180, height: 240 },
  file11: { width: 416, height: 234 },
  file12: { width: 416, height: 234 },
  scary_monsters_remake: { width: 312, height: 416 },
}

/**
 * What is on disk for each id: a clip or a still.
 *
 * Probed, not declared. The entry's own `kind` is editorial and can be wrong —
 * `file09` was flagged `photo` for months as an icon preview while being a
 * video — and a surface that renders an <img> for something with no image gets a
 * broken frame. This is the field that decides what is rendered.
 */
export const MEDIA_KIND: Record<string, 'video' | 'photo'> = {
  file10: 'video',
  file11: 'video',
  file12: 'video',
  scary_monsters_remake: 'photo',
}

/**
 * Content hashes of the shipped renditions, appended to their URLs as ?v=.
 * The filenames never change across edits and the host caches for 10 minutes,
 * so without this an edited poster stays invisible until the cache expires.
 */
export const MEDIA_VERSION: Record<string, { full: string; thumb: string; poster: string }> = {
  file10: { full: 'a7913ab4', thumb: 'fbbf41a0', poster: '47c260b0' },
  file11: { full: 'd0e70b44', thumb: 'b538ffcd', poster: '37fb111c' },
  file12: { full: 'd104fe7c', thumb: 'b9a48d99', poster: '5d3cabde' },
  scary_monsters_remake: { full: 'd107cca6', thumb: 'f3f020ff', poster: 'baafa1e6' },
}
