// GENERATED by scripts/gen-media-meta.mjs — do not edit by hand.
// Probed from public/media/*_full.{mp4,jpg}, the rendition the page displays.
// Regenerate with: npm run gen:media-meta

export type MediaMeta = { width: number; height: number; durationSec: number }

export const MEDIA_META: Record<string, MediaMeta> = {
  file01: { width: 1280, height: 720, durationSec: 10.43 },
  file02: { width: 1280, height: 720, durationSec: 10 },
  file03: { width: 1280, height: 720, durationSec: 12 },
  file04: { width: 1280, height: 720, durationSec: 12 },
  file05: { width: 1280, height: 720, durationSec: 12 },
  file06: { width: 1280, height: 720, durationSec: 10 },
  file07: { width: 406, height: 720, durationSec: 9.17 },
  file08: { width: 406, height: 720, durationSec: 5 },
  file09: { width: 720, height: 720, durationSec: 12 },
  file10: { width: 540, height: 720, durationSec: 5.03 },
  file11: { width: 1280, height: 720, durationSec: 9.97 },
  file12: { width: 1280, height: 720, durationSec: 12 },
}

/** The 240p encode's box. Only its aspect ratio matters, and only as a guard. */
export const THUMB_META: Record<string, { width: number; height: number }> = {
  file01: { width: 416, height: 234 },
  file02: { width: 416, height: 234 },
  file03: { width: 416, height: 234 },
  file04: { width: 416, height: 234 },
  file05: { width: 416, height: 234 },
  file06: { width: 416, height: 234 },
  file07: { width: 150, height: 266 },
  file08: { width: 150, height: 266 },
  file09: { width: 240, height: 240 },
  file10: { width: 180, height: 240 },
  file11: { width: 416, height: 234 },
  file12: { width: 416, height: 234 },
}

/**
 * What is on disk for each id: a clip or a still.
 *
 * Probed, not declared. The entry's own `kind` is editorial and can be wrong —
 * `file09` was flagged `photo` for months as an icon preview while being a
 * video — and a surface that renders an <img> for something with no image gets a
 * broken frame. This is the field that decides what is rendered.
 */
export const MEDIA_KIND: Record<string, 'video' | 'photo'> = {
  file01: 'video',
  file02: 'video',
  file03: 'video',
  file04: 'video',
  file05: 'video',
  file06: 'video',
  file07: 'video',
  file08: 'video',
  file09: 'video',
  file10: 'video',
  file11: 'video',
  file12: 'video',
}

/**
 * Content hashes of the shipped renditions, appended to their URLs as ?v=.
 * The filenames never change across edits and the host caches for 10 minutes,
 * so without this an edited poster stays invisible until the cache expires.
 */
export const MEDIA_VERSION: Record<string, { full: string; thumb: string; poster: string }> = {
  file01: { full: '0b35797a', thumb: 'ec097efd', poster: '964f8ee2' },
  file02: { full: 'ff8df29a', thumb: 'b6b5a62d', poster: '36c38728' },
  file03: { full: 'e60eed79', thumb: 'f588b91e', poster: 'cef4515b' },
  file04: { full: 'f66f40a9', thumb: '532698e0', poster: 'd49f2041' },
  file05: { full: 'f5bdb897', thumb: '6f46ec58', poster: '54b2b6d2' },
  file06: { full: 'bb7ab16d', thumb: '9f036096', poster: '2fc87fce' },
  file07: { full: '42ac4dc1', thumb: 'cd068aa9', poster: '323f804c' },
  file08: { full: '2c1918be', thumb: '24ced885', poster: 'fe80fa84' },
  file09: { full: 'e7ea6815', thumb: 'a640bc25', poster: 'a123aa16' },
  file10: { full: 'a7913ab4', thumb: 'fbbf41a0', poster: '47c260b0' },
  file11: { full: 'd0e70b44', thumb: 'b538ffcd', poster: '37fb111c' },
  file12: { full: 'd104fe7c', thumb: 'b9a48d99', poster: '5d3cabde' },
}
