// GENERATED by scripts/gen-media-meta.mjs — do not edit by hand.
// Probed from public/media/*_full.mp4, the encode the page actually plays.
// Regenerate with: npm run gen:media-meta

export type MediaMeta = { width: number; height: number; durationSec: number }

export const MEDIA_META: Record<string, MediaMeta> = {
  file01: { width: 1280, height: 720, durationSec: 10.43 },
  file02: { width: 1280, height: 720, durationSec: 10 },
  file03: { width: 1280, height: 720, durationSec: 12 },
  file04: { width: 1280, height: 720, durationSec: 12 },
  file05: { width: 1280, height: 720, durationSec: 12 },
  file06: { width: 1280, height: 720, durationSec: 10 },
  file07: { width: 406, height: 720, durationSec: 9.17 },
  file08: { width: 406, height: 720, durationSec: 5 },
  file09: { width: 720, height: 720, durationSec: 12 },
  file10: { width: 540, height: 720, durationSec: 5.03 },
  file11: { width: 1280, height: 720, durationSec: 9.97 },
  file12: { width: 1280, height: 720, durationSec: 12 },
}

/** The 240p encode's box. Only its aspect ratio matters, and only as a guard. */
export const THUMB_META: Record<string, { width: number; height: number }> = {
  file01: { width: 416, height: 234 },
  file02: { width: 416, height: 234 },
  file03: { width: 416, height: 234 },
  file04: { width: 416, height: 234 },
  file05: { width: 416, height: 234 },
  file06: { width: 416, height: 234 },
  file07: { width: 150, height: 266 },
  file08: { width: 150, height: 266 },
  file09: { width: 240, height: 240 },
  file10: { width: 180, height: 240 },
  file11: { width: 416, height: 234 },
  file12: { width: 416, height: 234 },
}
